inherit_from: .rubocop_todo.yml

# Extensions
# require: is being deprecated for plugins:
# https://docs.rubocop.org/rubocop/plugin_migration_guide.html.
require:
  - rubocop-factory_bot

plugins:
  - rubocop-rails
  - rubocop-rspec

# Enable any new cops
AllCops:
  NewCops: enable

# --- CUSTOM CONFIGURATION ---

# Especially with JWTs need more MemoizedHelpers
# than the default 5
RSpec/MultipleMemoizedHelpers:
  Max: 7
