#!/usr/bin/env ruby
# ----------------------------------------------------------------------
# Simple script to query healthchecks of locally running Ruby
#  applications. Generally intended as a healthchecks for
# container orchestration so curl/wget are not needed
# ----------------------------------------------------------------------
require 'net/http'
require 'uri'

def z_endpoint(endpoint)
  puts "[#{endpoint}]"
  host = ENV.fetch('HOST', 'localhost')
  port = ENV.fetch('PORT', 3000)
  "http://#{host}:#{port}/#{endpoint}z"
end

endpoint = ARGV.shift || 'ready'
healthcheck = URI.parse(z_endpoint(endpoint))

begin
  response = Net::HTTP.get_response(healthcheck)
rescue StandardError
  exit(1)
end

# rubocop:disable Style/TernaryParentheses
puts "Healthcheck [#{healthcheck}] returned code: [#{response.code}] body: [#{response.body}]"
exit_code = (response.code == '200') ? 0 : 1
# rubocop:enable Style/TernaryParentheses
exit(exit_code)
