version: '3.8'
services:
  app:
    image: brianjbayer/random_thoughts_api:${APP_TAG:-latest}
    container_name: ${APP_HOSTNAME:-app}
    environment:
      - RAILS_LOG_TO_STDOUT
      - SECRET_KEY_BASE
      - APP_JWT_SECRET
