services:
  app:
    image: brianjbayer/random_thoughts_api:${APP_TAG:-latest}
    container_name: ${APP_HOSTNAME:-app}
    environment:
      # App-specific configuration
      - APP_JWT_SECRET
      # Rails (Puma) configuration
      - PIDFILE
      - PORT
      - RACK_ENV
      - RAILS_ENV
      - RAILS_ASSUME_SSL
      - RAILS_FORCE_SSL
      - RAILS_LOG_LEVEL
      - RAILS_LOG_TO_STDOUT
      - RAILS_MAX_THREADS
      - RAILS_MIN_THREADS
      - RAILS_SERVE_STATIC_FILES
      - SECRET_KEY_BASE
      - WEB_CONCURRENCY
    ports:
      # Set localhost port to not conflict with e2e environment
      - ${APP_LOCALHOST_PORT:-13000}:${PORT:-3000}
    expose:
      - ${PORT:-3000}
    healthcheck:
      test: ["CMD", "bash", "-c", "ruby", "app_is", "ready"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 10
