services:
  app:
    command: ./entrypoint.sh

  e2etests:
    # Pin tag to ensure version matching between tests and app
    image: "${E2ETESTS_IMAGE:-brianjbayer/random_thoughts_api_e2e:5fbcb40870f546830472701113cd3802f93cdb84}"
    container_name: ${E2ETESTS_HOSTNAME:-e2etests}
    environment:
      - E2E_BASE_URL=http://${APP_HOSTNAME:-app}:${PORT:-3000}
    depends_on:
      app:
        condition: service_healthy
