services:
  app:
    environment:
      PGPORT: ${PGPORT:-5432}
      # Is (matches) the db service
      POSTGRES_HOST: ${POSTGRES_HOST:-db}
      POSTGRES_DB: ${POSTGRES_DB:-random_thoughts_api}_${RAILS_ENV:-development}
      POSTGRES_USER: ${POSTGRES_USER:-random_thoughts_api}_${RAILS_ENV:-development}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-banana}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    environment:
      # PostgreSQL environment variables
      # By default Postgres runs on port 5432
      PGPORT: ${PGPORT:-5432}
      # For happy container (logs), set internal user to POSTGRES_DB/POSTGRES_USER
      PGUSER: ${PGUSER:-random_thoughts_api}_${RAILS_ENV:-development}
      # Postgres image environment variables
      # To keep the pg container (logs) happy, make db and user the same
      POSTGRES_DB: ${POSTGRES_DB:-random_thoughts_api}_${RAILS_ENV:-development}
      POSTGRES_USER: ${POSTGRES_USER:-random_thoughts_api}_${RAILS_ENV:-development}
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-banana}
    ports:
    # Maps to host localhost port 5432
    - "${PGPORT:-5432}:5432"
    # Expose Port to other containers in this network
    expose:
    - ${PGPORT:-5432}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
