apiVersion: v1
kind: Service
metadata:
  name: random-thoughts-api
  namespace: random-thoughts-api
spec:
  type: NodePort
  selector:
    app: random-thoughts-api
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-thoughts-api
  namespace: random-thoughts-api
spec:
  selector:
    matchLabels:
      app: random-thoughts-api
  template:
    metadata:
      labels:
        app: random-thoughts-api
    spec:
      containers:
        - name: random-thoughts-api
          # image: brianjbayer/random_thoughts_api
          image: rta
          imagePullPolicy: IfNotPresent
          env:
            # Assume using dependencies postgres service
            - name: POSTGRES_HOST
              value: postgres
            # Share postgres ConfigMap
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_PASSWORD
            # App configmap
            - name: RAILS_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RAILS_ENV
            - name: RAILS_LOG_TO_STDOUT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: RAILS_LOG_TO_STDOUT
            - name: APP_JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: APP_JWT_SECRET
            - name: SECRET_KEY_BASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SECRET_KEY_BASE
          livenessProbe:
            httpGet:
              path: /livez
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
