---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/random_thoughts":
    get:
      summary: list random_thoughts
      parameters:
      - name: page
        in: query
        description: page number
        required: false
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/paginated_random_thoughts"
    post:
      summary: create random_thought
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/random_thought"
        '400':
          description: bad request
          content:
            application/json:
              examples:
                empty_request:
                  value:
                    status: 400
                    error: bad_request
                    message: param is missing or the value is empty:...
                invalid_request:
                  value:
                    status: 400
                    error: bad_request
                    message: Error occurred while parsing request parameters
              schema:
                "$ref": "#/components/schemas/error"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/new_random_thought"
  "/random_thoughts/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show random_thought
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/random_thought"
        '404':
          description: not found
          content:
            application/json:
              examples:
                not_found:
                  value:
                    status: 404
                    error: not_found
                    message: Couldn't find RandomThought with 'id'=??
              schema:
                "$ref": "#/components/schemas/error"
        '500':
          description: internal server error
          content:
            application/json:
              examples:
                internal_server_error:
                  value:
                    status: 500
                    error: internal_server_error
                    message: "..."
              schema:
                "$ref": "#/components/schemas/error"
    patch:
      summary: update random_thought
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/random_thought"
        '404':
          description: not found
          content:
            application/json:
              examples:
                not_found:
                  value:
                    status: 404
                    error: not_found
                    message: Couldn't find RandomThought with 'id'=??
              schema:
                "$ref": "#/components/schemas/error"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/update_random_thought"
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
- url: http://localhost:3000
  description: Local development
components:
  schemas:
    new_random_thought:
      type: object
      properties:
        thought:
          type: string
        name:
          type: string
      required:
      - thought
      - name
    random_thought:
      type: object
      properties:
        id:
          type: integer
        thought:
          type: string
        name:
          type: string
      required:
      - id
      - thought
      - name
    update_random_thought:
      type: object
      properties:
        thought:
          type: string
        name:
          type: string
    paginated_random_thoughts:
      type: object
      properties:
        data:
          type: array
          items:
            "$ref": "#/components/schemas/random_thought"
        meta:
          "$ref": "#/components/schemas/pagination"
      required:
      - data
      - meta
    pagination:
      type: object
      properties:
        current_page:
          type: integer
        next_page:
          type: integer
          nullable: true
        prev_page:
          type: integer
          nullable: true
        total_pages:
          type: integer
        total_count:
          type: integer
      required:
      - current_page
      - next_page
      - prev_page
      - total_pages
      - total_count
    error:
      type: object
      properties:
        status:
          type: integer
        error:
          type: string
        message:
          type: string
      required:
      - status
      - error
      - message
