#!/bin/sh
set -e

usage() {
  cat << USAGE
Usage: $0 [-cdehop] [CMD]
This script orchestrates 'docker compose run app' using the docker compose framework
  * Arguments are passed to the app service as the CMD (entrypoint)
  * Environment variables override app and framework defaults

OPTIONS: (in override order)
  -o: Run only the application (no other services)
  -d: Run the docker-compose Dev environment
  -c: Run the docker-compose CI environment (must specify APP_IMAGE)

Other Options:
  -e: Run the e2e tests (against the app service)
  -p: Run the performance tests (against the app service)
USAGE
}

err_exit() {
  err_code=$1
  err_msg="$2"
  echo "${err_msg}  --  Exit:[${err_code}]" 1>&2
  exit $err_code
}

# Handle options
while getopts ":cdehop" options; do
  case "${options}" in
    c)
      ci=1
      ;;
    d)
      devenv=1
      ;;
    e)
      run_e2etests=1
      ;;
    h)
      usage ; exit
      ;;
    o)
      app_only=1
      ;;
    p)
      run_perftests=1
      ;;
    \?)
      usage
      err_exit 1 "Invalid Option: -$OPTARG"
      ;;
  esac
done
shift $((OPTIND-1))

[ ! -z ${run_perftests+x} ] && [ ! -z ${run_e2etests} ] \
  && err_exit 2 "Can not use both '-e' and '-p' options"

echo "DOCKER VERSION: [`docker --version`]"

docker_compose_command='docker compose -f docker-compose.yml '
[ -z ${app_only} ] && docker_compose_command="${docker_compose_command} -f docker-compose.db.yml "
[ ! -z ${devenv} ] && docker_compose_command="${docker_compose_command} -f docker-compose.dev.yml "
[ ! -z ${ci} ] && docker_compose_command="${docker_compose_command} -f docker-compose.ci.yml "

# Default is to run the app, but must specify --service-ports
# (by default docker compose run does not expose host ports)
run_command='run --rm --service-ports app '

if [ ! -z ${run_perftests} ]; then
  docker_compose_command="${docker_compose_command} -f docker-compose.perf.yml "
  run_command='run --rm perftests '
fi

if [ ! -z ${run_e2etests} ]; then
  docker_compose_command="${docker_compose_command} -f docker-compose.e2e.yml "
  run_command='run --rm e2etests '
fi

docker_compose_run_command="${docker_compose_command} ${run_command}"
echo "DOCKER COMPOSE RUN COMMAND: [${docker_compose_run_command}]"

echo 'DOCKER COMPOSE CONFIGURATION...'
$docker_compose_command config

echo 'DOCKER COMPOSE PULLING...'
set +e ; $docker_compose_command pull ; set -e

echo "DOCKER COMPOSE RUNNING [${docker_compose_run_command}] [$@]..."
# Allow to fail but catch return code
set +e
${docker_compose_run_command} "$@"
run_return_code=$?
set -e

run_disposition='SUCCESS' ; [ $run_return_code -eq 0 ] || run_disposition='FAIL'
echo "DOCKER COMPOSE RUN [${run_disposition}] WITH RETURN CODE [${run_return_code}]"

echo 'DOCKER-COMPOSE DOWN...'
$docker_compose_command down

echo "EXIT: ${run_disposition} [${run_return_code}]"
exit $run_return_code
