#!/bin/sh
set -e

usage() {
  cat << USAGE
This script orchestrates the kubernetes environment

OPTIONS:
  -o: Do not apply nginx-ingress controller
  -h: Help information

Usage: $0 [-ho] [apply | delete] [FILENAME]
USAGE
}

err_exit() {
  err_code=$1
  err_msg="$2"
  echo "${err_msg}  --  Exit:[${err_code}]" 1>&2
  exit $err_code
}

# Handle options
while getopts ":ho" options; do
  case "${options}" in
    h)
      usage ; exit
      ;;
    o)
      no_ingress=1
      ;;
    \?)
      usage
      err_exit 1 "Invalid Option: -$OPTARG"
      ;;
  esac
done
shift $((OPTIND-1))

# This script relies on kubectl
kubectl_cli='kubectl'
${kubectl_cli} version || err_exit 127 "The ${kubectl_cmd} command is required"

# The kubectl command (assumed 'apply' or 'deploy')
command="$1"
shift
kubectl_command="${kubectl_cli} ${command}"

echo "K8s RUN [${kubectl_command} -f $@ ]..."


INGRESS_NGINX_VERSION="${INGRESS_NGINX_VERSION:=v1.10.1}"
INGRESS_NGINX="https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-${INGRESS_NGINX_VERSION}/deploy/static/provider/cloud/deploy.yaml"

if [ -z "${no_ingress}" ] ; then
  echo "STARTING NGINX INGRESS CONTROLLER [${INGRESS_NGINX_VERSION}]..."
  ${kubectl_command} -f "${INGRESS_NGINX}"

  echo "WAITING FOR NGINX INGRESS POD..."
  # FROM https://kubernetes.github.io/ingress-nginx/deploy/#pre-flight-check
  ${kubectl_cli} wait --namespace ingress-nginx \
  --for=condition=ready pod \
  --selector=app.kubernetes.io/component=controller \
  --timeout=120s

  # Still give it a few
  INGRESS_NGINX_SLEEP=${INGRESS_NGINX_SLEEP:=15}
  i=${INGRESS_NGINX_SLEEP}
  while [ "$i" -gt 1 ]; do printf "."; sleep 1 ; i=$((i-1)); done ; echo ''
fi

echo "RUNNING [${kubectl_command} -f $@ ]"
${kubectl_command} -f "$@"
